version: '3'

networks:
  securintx_blog_hugo_net:
    driver: bridge


services:

  hugo:
    image: klakegg/hugo:alpine
    container_name: securintx_blog_hugo
    user: ${CURRENT_UID}
    command: help
    volumes:
      - ".:/src"

  serve:
    image: klakegg/hugo:alpine
    container_name: securintx_blog
    user: ${CURRENT_UID}
    restart: unless-stopped
    command: ["server", "--watch" , "-D"]
    volumes:
      - "./:/src"
    networks: 
      - securintx_blog_hugo_net
    ports:
      - $HTTP_PORT:1313